websites:
  - keywords:
      - 百度
      - 百度一下
    url: "https://www.baidu.com"
  - keywords:
      - 谷歌
    url: "https://www.google.com"
  - keywords:
      - ChatGPT
      - 拆的这边去
      - 拆的鸡皮
    url: "https://chatgpt.com"
